version: "3"
 
services:

  dashboard:
    user: "1000" # Security measure: Run as non-root
    container_name: dashboard
    hostname: dashboard
    restart: unless-stopped
    build:
      context: ./services/dashboard/
      dockerfile: ./Dockerfile
    # working_dir: /app
    ports:
      - "81:5555"
    networks:
      - traefik
    command: ["/bootstrap.sh","python /Landing_Page.py"]
    volumes:
      - ./vault-bootstrap/bootstrap.sh:/bootstrap.sh
      - ./vault-bootstrap/bootstrap.env:/bootstrap.env
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/dashboard/Landing_Page.py:/Landing_Page.py
      - ./services/dashboard/templates/:/templates
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`, `dashboard.traefik.internal`,`dashboard.int`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=dashboard, dashboard-auth"

      - "traefik.http.services.dashboard.loadbalancer.server.port=5555"
      - "traefik.http.services.dashboard.loadbalancer.server.scheme=http"

      - "traefik.http.middlewares.dashboard.stripprefix.prefixes=/dashboard"
      - "traefik.http.middlewares.dashboard.stripprefix.forceSlash=false"
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/htpasswd.txt"

  
  
  # Services - LLM
  # ============================

  huggingface:
    user: "1000" # Security measure: Run as non-root
    container_name: huggingface
    build:
      context: ./
      dockerfile: ./services/llm/huggingface/.Dockerfile
    ports:
      - "${HUGGINGFACE_PORT}:7860"
    volumes:
      - ./services/llm/huggingface/app:/app
    tty: true
    restart: unless-stopped
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'


  # Services Development Environment
  # =============================


  vulnlab:
    # user: "1000" # Security measure: Run as non-root
    container_name: vulnlab
    hostname:  vulnlab  
    build:
      context: ./
      dockerfile: ./services/vulnlab/.Dockerfile
    # ports:
    #   - 1337:80
    environment:
      - NAME=vulnlab # used in bootstrap
    restart: unless-stopped
    networks:
      - traefik
      - vault
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.vulnlab.rule=Host(`vulnlab.localhost`, `vulnlab.int`, `vulnlab.traefik.internal`) || PathPrefix(`/vulnlab`)"
      - "traefik.http.routers.vulnlab.tls=true"
      - "traefik.http.routers.vulnlab.tls.certresolver=myresolver"
      - "traefik.http.services.vulnlab.loadbalancer.server.port=80"
      # - "traefik.http.routers.vulnlab.entrypoints=web"
      - "traefik.http.middlewares.vulnlab.stripprefix.prefixes=/vulnlab"
      - "traefik.http.middlewares.vulnlab.stripprefix.forceSlash=false"
      - "function.port.80=Vulnerability Playground"


  it-tools:
    # user: "1000" # Security measure: Run as non-root
    container_name: it-tools
    hostname:  it-tools  
    build:
      context: ./
      dockerfile: ./services/it-tools/.Dockerfile
    restart: unless-stopped
    ports:
      - 8880:80
    networks:
      - traefik
      - vault
    # volumes:
    #   - ./vault-bootstrap/bootstrap.sh:/secret/bootstrap.sh
    #   - ./vault-bootstrap/bootstrap.env:/secret/bootstrap.env
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.tools.rule=Host(`tools.localhost`, `tools.int`, `tools.traefik.internal`) || PathPrefix(`/tools`)"
      
      - "traefik.http.routers.tools.tls=true"
      - traefik.http.routers.tools.tls.certresolver=myresolver
      - "traefik.http.services.tools.loadbalancer.server.port=80"
      # - "traefik.http.routers.tools.entrypoints=web"
      - "traefik.http.middlewares.tools.stripprefix.prefixes=/tools"
      - "traefik.http.middlewares.tools.stripprefix.forceSlash=false"
      - "function.port.80=Vulnerability Playground"


  dev-environment:
    # user: "1000" # Security measure: Run as non-root
    container_name: dev-environment
    hostname: dev-environment
    build:
      context: ./
      dockerfile: ./services/dev-environment/.Dockerfile
    user: 1000:1000
    restart: unless-stopped
    environment:
      - DEV_HTTP_PORT=${DEV_HTTP_PORT}
      - IP_ADDRESS=${IP_ADDRESS}
      - DOCKER_USER=1000
      - PASSWORD=${ADMIN_PASSWORD}
      # - CERT_FILE=/etc/ssl/certs/cert.pem
      # - KEY_FILE=/etc/ssl/private/key.pem
    ports:
      - "${DEV_ENVIRONMENT_PORT}:8080"
    networks:
      - traefik
      - vault
    volumes:
      -  ${DEV_ROOT}:/home/coder/
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dev-environment.rule=Host(`dev-environment.localhost`, `dev-environment.traefik.internal`, `dev-environment.int`) || PathPrefix(`/dev-environment`)"
      # - "traefik.http.routers.dev-environment.tls=true"
      - "traefik.http.routers.dev-environment.middlewares=dev-environment, dev-environment-auth, test-ipwhitelist"

      - "traefik.http.services.dev-environment.loadbalancer.server.port=8080"
      - "traefik.http.services.dev-environment.loadbalancer.server.scheme=http"

      - "traefik.http.middlewares.dev-environment.stripprefix.prefixes=/dev-environment"
      - "traefik.http.middlewares.dev-environment.stripprefix.forceSlash=false"
      - "traefik.http.middlewares.test-ipwhitelist.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.3.201, 192.168.3.196"
      - "traefik.http.middlewares.dev-environment-auth.basicauth.usersfile=/htpasswd.txt"


  python-bootstrap:
    user: "1000" # Security measure: Run as non-root
    hostname: python-bootstrap
    build:
      context: ./services/python_bootstrap/
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - ./services/python_bootstrap/app:/app
    environment:
      - GIT_REPO_URL:""
      - GIT_PULL:"true"
      - MAIN_PY_FILE:"app.py"
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'
    # ports:
    #   - "5001:5000"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.python-bootstrap.rule=Host(`python-bootstrap.localhost`, `python-bootstrap.traefik.internal`, `pythonbootstrap.int`) || PathPrefix(`/python-bootstrap`)"
      - "traefik.http.routers.python-bootstrap.tls=true"
      - "traefik.http.routers.python-bootstrap.middlewares=python-bootstrap"

      - "traefik.http.services.python-bootstrap.loadbalancer.server.port=5000"
      - "traefik.http.services.python-bootstrap.loadbalancer.server.scheme=https"

      - "traefik.http.middlewares.python-bootstrap.stripprefix.prefixes=/python-bootstrap"
      - "traefik.http.middlewares.python-bootstrap.stripprefix.forceSlash=false"


  game-scanner:
    # user: "1000" # Security measure: Run as non-root
    #note the above is disabled because the tls cert chain module needs root - need to find workaround
    container_name: game-scanner
    hostname: game-scanner
    build:
      context: ./
      dockerfile: ./services/game_scanner/Dockerfile
    working_dir: /app
    volumes:
      - ./services/game_scanner/app:/app
    environment:
      - GIT_REPO_URL:""
      - GIT_PULL:"true"
      - MAIN_PY_FILE:"gsheetoauth.py"
    ports:
      - "5000:5000"  
    networks:
      - traefik
      # - webrequests 
    logging:
        driver: fluentd
        options:
          fluentd-async-connect: 'true'
          fluentd-address: '192.168.3.201:24224'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.game-scanner.rule=Host(`game-scanner.localhost`, `game-scanner.traefik.internal`, `game-scanner.int`) || PathPrefix(`/game-scanner`)"
      - "traefik.http.routers.game-scanner.tls=true"
      - "traefik.http.routers.game-scanner.middlewares=game-scanner"

      - "traefik.http.services.game-scanner.loadbalancer.server.port=5000"
      - "traefik.http.services.game-scanner.loadbalancer.server.scheme=https"

      - "traefik.http.middlewares.game-scanner.stripprefix.prefixes=/game-scanner"
      - "traefik.http.middlewares.game-scanner.stripprefix.forceSlash=false"


  # Servers
  # ==============================
  alpine-server:
    user: "1000" # Security measure: Run as non-root
    build:
      context: ./
      dockerfile: ./server/alpine/.Dockerfile
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}
        ALPINE_DIGEST : ${ALPINE_DIGEST}
        SERVER_REPO : ${SERVER_REPO}
        GITHUB_TOKEN : ${GITHUB_TOKEN}
        GITHUB_USERNAME : ${GITHUB_USERNAME}
    ports:
      - "${ALPINE_SERVER_PORT}:8000"
    volumes:
      - ./server/alpine/app:/app
    tty: true
    environment:
      - SERVER_MODE=${SERVER_MODE}
    restart: unless-stopped


  ubuntu-server:
    user: "1000" # Security measure: Run as non-root
    build:
      context: ./
      dockerfile: ./server/ubnutu/.Dockerfile
      args:
        UBUNTU_SERVER_IMAGE: ${UBUNTU_SERVER_IMAGE}
        UBUNTU_SERVER_DIGEST : ${UBUNTU_SERVER_DIGEST}
        SERVER_REPO : ${SERVER_REPO}
        GITHUB_TOKEN : ${GITHUB_TOKEN}
        GITHUB_USERNAME : ${GITHUB_USERNAME}
    ports:
      - "${UBUNTU_SERVER_PORT}:8000"
    volumes:
      - ./server/Alpine/app:/app
    tty: true
    environment:
      - SERVER_MODE=${SERVER_MODE}
    restart: unless-stopped

  # Clients - Headless
  # ==============================
 
  android-client:
    user: "1000" # Security measure: Run as non-root
    build:
      context: ./
      dockerfile: ./client/android/.Dockerfile
      args:
        ANDROID_IMAGE: ${ANDROID_IMAGE}
        ANDROID_DIGEST : ${ANDROID_DIGEST}
        CLIENT_REPO : ${CLIENT_REPO}
        GITHUB_TOKEN : ${GITHUB_TOKEN}
        GITHUB_USERNAME : ${GITHUB_USERNAME}
    volumes:
      - ./clientandroid/app:/app
    environment:
      - CLIENT_MODE=${CLIENT_MODE}

  osx-client:
    user: "1000" # Security measure: Run as non-root
    build:
      context: ./
      dockerfile: ./client/osx/.Dockerfile
      args:
        OSX_IMAGE: ${OSX_IMAGE}
        OSX_DIGEST : ${OSX_DIGEST}
        CLIENT_REPO : ${CLIENT_REPO}
        GITHUB_TOKEN : ${GITHUB_TOKEN}
        GITHUB_USERNAME : ${GITHUB_USERNAME}
    volumes:
      - ./client/osx/app:/app
    environment:
      - CLIENT_MODE=${CLIENT_MODE} 


  ubuntu-client:
    user: "1000" # Security measure: Run as non-root
    build:
      context: ./
      dockerfile: ./client/ubuntu/.Dockerfile
      args:
        UBUNTU_IMAGE : ${UBUNTU_IMAGE}
        UBUNTU_DIGEST : ${UBUNTU_DIGEST}
        CLIENT_REPO : ${CLIENT_REPO}
        GITHUB_TOKEN : ${GITHUB_TOKEN}
        GITHUB_USERNAME : ${GITHUB_USERNAME}
    ports:
      - "${UBUNTU_CLIENT_PORT}:8000"
    volumes:
      - ./client/ubuntu/app:/app
    environment:
      - CLIENT_MODE=${CLIENT_MODE}
      - CLIENT_REPO=${CLIENT_REPO}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
    # command: /bin/bash
    tty: true

# Volumes
# ==============================
volumes:
  
  pgdata:
  
  logs:
  
  crowdsec-db:

  crowdsec-config:


# Networks
# ==============================
networks:

  webrequests:
    # external: true

  logging:  
    external: true

  postgres:
    external: true

  traefik:
    external: true
  
  vault:
    external: true
  

# Example composition (old)
#======================
# # Set the operating mode
# SERVER_MODE="normal" CLIENT_MODE="normal"\ 
#
# # Set the version digest (aquired from hub.docker.com)
# SERVER_DIGEST="@sha:1234abcd..." IOS_DIGEST="@sha:1234abcd..." \
#
# # Set the target repos
# SERVER_REPO="https://github.com/..." CLIENT_REPO="https://github.com/..."\
#
# # Compose the testbench
# docker compose up server ios-client
#
# This will start both a server and IOS client container connected on a network
#
# docker compose run -e SERVER_MODE="normal" CLIENT_MODE="normal"\ 
# -e SERVER_DIGEST="sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d" -e UBNUTU_DIGEST="sha256:7a57c69fe1e9d5b97c5fe649849e79f2cfc3bf11d10bbd5218b4eb61716aebe6"
# -e SERVER_REPO="https://gist.github.com/BoeJaker/86659a8e647496a5f5b24b33048f739a" -e CLIENT_REPO="https://gist.github.com/BoeJaker/6d30208bd42b3769f593a9e95e29a873"\
# server ubuntu-client
#
#You can also set environment variables via the .env file, see env.dummy for more info
#
# See REAME.md for more information
